addSbtPlugin("com.dwijnand"              % "sbt-dynver"   % "4.1.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.2.3")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix" % "0.10.0")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"   % "5.6.5")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly" % "1.2.0")
addSbtPlugin("io.spray"                  % "sbt-revolver" % "0.9.1")
