---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
    - master
  pull_request:

jobs:
  checks:
    name: Format and style checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v7
      with:
        java-version: adopt@1.14
    - run: sbt ";scalafixAll --check"
    - run: sbt scalafmtCheckAll
    - run: sbt scalafmtSbtCheck
    - run: sbt headerCheckAll
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v1.0.0

  test:
    name: Compile and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v7
      with:
        java-version: adopt@1.14
    - run: sbt test
